Add clse_v1.1, which includes parsed linguistic attributes from the linguistic signature, with accompanying script.
google-research-datasets/clse pull request #1
Opened 2022-11-23 16:10 UTC by justinxzhao

Additional changes:
- Update gitignore
- Add pre-commit to lint/de-flake python files

2022-11-23 16:11 UTC, justinxzhao commented
CLA check has been signed. :)

2022-11-23 17:06 UTC, varepsilon commented on scripts/generate_v1.1_data.py
> +        reduced_linguistic_signature = reduced_linguistic_signature.replace(
here you are not checking that those are really prefixes. I suggest you strip the prefixes down below instead

2022-11-23 17:06 UTC, varepsilon commented on scripts/generate_v1.1_data.py
> +        components = attribute.split(":")
split(":", 1)

2022-11-23 17:14 UTC, varepsilon commented on scripts/generate_v1.1_data.py
> +        attribute_map[components[0]] = components[1]
for prefix in VERBOSE_SIGNATURE_PREFIXES:
  name = name.removeprefix(prefix)
attribute_map[name] = value

2022-11-23 17:19 UTC, varepsilon requested changes

2022-11-23 17:19 UTC, varepsilon commented on scripts/generate_v1.1_data.py
> +            all_attributes.update(list(attribute_map.keys()))
are you sure you need to create a list and can't update directly from keys()?

2022-11-23 17:19 UTC, varepsilon commented on scripts/generate_v1.1_data.py
> +    return sorted(list(all_attributes))
sorted(all_attributes) should work too

2022-11-26 23:29 UTC, justinxzhao reviewed
Thanks for the review!

2022-11-26 23:29 UTC, justinxzhao commented on scripts/generate_v1.1_data.py
> +        reduced_linguistic_signature = reduced_linguistic_signature.replace(
Done.

2022-11-26 23:29 UTC, justinxzhao commented on scripts/generate_v1.1_data.py
> +        attribute_map[components[0]] = components[1]
Done.

2022-11-26 23:29 UTC, justinxzhao commented on scripts/generate_v1.1_data.py
> +    return sorted(list(all_attributes))
Done.

2022-11-26 23:29 UTC, justinxzhao commented on scripts/generate_v1.1_data.py
> +            all_attributes.update(list(attribute_map.keys()))
Done.

2022-11-26 23:29 UTC, justinxzhao commented on scripts/generate_v1.1_data.py
> +        components = attribute.split(":")
Done.

2022-11-28 09:23 UTC, varepsilon approved these changes
Thanks!

2022-11-28 09:23 UTC, merged